# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectspost', '0002_auto_20190403_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='profile_photo',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='user',
        ),
    ]
