# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 09:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectspost', '0004_moringamerch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to=b'projects/')),
                ('description', models.TextField(max_length=500)),
                ('link', models.TextField(null=True, validators=[django.core.validators.URLValidator()])),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MoringaMerch',
        ),
    ]
