# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectspost', '0005_auto_20190405_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmerch',
            name='profile',
        ),
        migrations.DeleteModel(
            name='ProjectMerch',
        ),
    ]
